### ISSUE TITLE
No module named 'pytest_xray_server.plugin'; 'pytest_xray_server' is not a package

### ISSUE THREAD

**Issue by nemozny** [lexa/pytest-xray-server#1]
Windows
```
pip --version
pip 21.1.2 from c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\pip (python 3.8)
python --version
Python 3.8.0
```
Immediately after installation is pytest giving me
```
> pytest
Traceback (most recent call last):
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\runpy.py", line 192, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "C:\Users\n7nuaf\AppData\Local\Programs\Python\Python38-32\Scripts\pytest.exe\__main__.py", line 7, in <module>
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py", line 185, in console_main
    code = main()
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py", line 143, in main
    config = _prepareconfig(args, plugins)
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py", line 318, in _prepareconfig
    config = pluginmanager.hook.pytest_cmdline_parse(
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\hooks.py", line 286, in __call__
    return self._hookexec(self, self.get_hookimpls(), kwargs)
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py", line 93, in _hookexec
    return self._inner_hookexec(hook, methods, kwargs)
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py", line 84, in <lambda>
    self._inner_hookexec = lambda hook, methods, kwargs: hook.multicall(
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py", line 203, in _multicall
    gen.send(outcome)
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\helpconfig.py", line 100, in pytest_cmdline_parse
    config: Config = outcome.get_result()
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py", line 80, in get_result
    raise ex[1].with_traceback(ex[2])
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\callers.py", line 187, in _multicall
    res = hook_impl.function(*args)
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py", line 1003, in pytest_cmdline_parse
    self.parse(args)
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py", line 1283, in parse
    self._preparse(args, addopts=addopts)
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\_pytest\config\__init__.py", line 1172, in _preparse
    self.pluginmanager.load_setuptools_entrypoints("pytest11")
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\site-packages\pluggy\manager.py", line 299, in load_setuptools_entrypoints
    plugin = ep.load()
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\importlib\metadata.py", line 75, in load
    module = import_module(match.group('module'))
  File "c:\users\n7nuaf\appdata\local\programs\python\python38-32\lib\importlib\__init__.py", line 127, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "<frozen importlib._bootstrap>", line 1014, in _gcd_import
  File "<frozen importlib._bootstrap>", line 991, in _find_and_load
  File "<frozen importlib._bootstrap>", line 970, in _find_and_load_unlocked
ModuleNotFoundError: No module named 'pytest_xray_server.plugin'; 'pytest_xray_server' is not a package
```
I have to uninstall pytest_xray_server in order to use pytest again.
I can't even do "pytest --trace-config", it also produces this error.
If I uninstall the package, it gets back to normal.

**Comment by lexa** [comment]
How did you install pytest and the plugin? Did you use '--user' when using via pip?

**Comment by nemozny** [comment]
Thanks, I did now, but no change.
It looks like my workstation is messed up, I have Anaconda's python and regular python.
If I switched to conda's in vscode, it is not producing errors. Although I've installed the package exactly the same way.
Maybe there some conflict in the "pytest.exe" executable?

**Comment by nemozny** [comment]
I'll close this, it's an issue on my workstation. Your package works in my conda environment, but not Python.

Works now!
This is what I was looking for
```
@pytest.mark.xray(test_key="CLD-1295", test_exec_key="CLD-1298")
```
It'll be good to include it on the example page.
Thanks you, @lexa.
